name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines the environment variables that are available to all jobs and steps in this workflow
    env:
      DOCKER_IMAGE: soraka:latest
      DOCKER_INSTANCE: soraka-instance

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/Soraka
            git pull origin main
            docker stop {{ env.DOCKER_INSTANCE }}
            docker build -t {{ env.DOCKER_IMAGE }} .
            docker run -d --restart unless-stopped   -e "DISCORD_TOKEN=MTEwNTkzMzQ3NDE2ODMyNDI3OA.Gm1sNu.CpM60L6_rEALTdYid_3dkEoL5YlRk6qMgIJghg"   -e "DISCORD_CLIENT_ID=1105933474168324278"   -e "DISCORD_GUILD_ID=952157949516730398"   -e "DISCORD_DEFAULT_PERMISSION_GROUP=1106292900775608430"   -e "RIOT_GAMES_DEVELOPER_API_KEY=RGAPI-18614f4c-e9fe-4b6e-9293-9c33e5fc5550"   --name {{ env.DOCKER_INSTANCE }} {{ env.DOCKER_IMAGE }}
