name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defines the environment variables that are available to all jobs and steps in this workflow
    env:
      DOCKER_REPO: soraka
      DOCKER_TAG: latest
      DOCKER_INSTANCE: soraka-instance

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/Soraka
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/soraka
            git pull origin main
            docker stop ${{ env.DOCKER_INSTANCE }} || true
            docker rm ${{ env.DOCKER_INSTANCE }} || true
            docker build -t ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }} .
            docker run \
            -d --restart unless-stopped \
            -e "FIREBASE_CREDENTIALS_BASE64=${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" \
            -e "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" \
            -e "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" \
            -e "DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}" \
            -e "DISCORD_DEFAULT_PERMISSION_GROUP=${{ secrets.DISCORD_DEFAULT_PERMISSION_GROUP }}" \
            -e "RIOT_GAMES_DEVELOPER_API_KEY=${{ secrets.RIOT_GAMES_DEVELOPER_API_KEY }}" \
            --name ${{ env.DOCKER_INSTANCE }} \
            ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
